/**
 * @fileoverview gRPC-Web generated client stub for grpcMobileGatewayService
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.2
// source: MobileGateway.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.grpcMobileGatewayService = require('./MobileGateway_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.grpcMobileGatewayService.Empty_Request,
 *   !proto.grpcMobileGatewayService.String_Response>}
 */
const methodDescriptor_grpcMobileGatewayService_HealthCheck = new grpc.web.MethodDescriptor(
  '/grpcMobileGatewayService.grpcMobileGatewayService/HealthCheck',
  grpc.web.MethodType.UNARY,
  proto.grpcMobileGatewayService.Empty_Request,
  proto.grpcMobileGatewayService.String_Response,
  /**
   * @param {!proto.grpcMobileGatewayService.Empty_Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.grpcMobileGatewayService.String_Response.deserializeBinary
);


/**
 * @param {!proto.grpcMobileGatewayService.Empty_Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.grpcMobileGatewayService.String_Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.grpcMobileGatewayService.String_Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServiceClient.prototype.healthCheck =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/HealthCheck',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_HealthCheck,
      callback);
};


/**
 * @param {!proto.grpcMobileGatewayService.Empty_Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.grpcMobileGatewayService.String_Response>}
 *     Promise that resolves to the response
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServicePromiseClient.prototype.healthCheck =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/HealthCheck',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_HealthCheck);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.grpcMobileGatewayService.SubcribeEvents_Request,
 *   !proto.grpcMobileGatewayService.Empty_Response>}
 */
const methodDescriptor_grpcMobileGatewayService_SubcribeEvents = new grpc.web.MethodDescriptor(
  '/grpcMobileGatewayService.grpcMobileGatewayService/SubcribeEvents',
  grpc.web.MethodType.UNARY,
  proto.grpcMobileGatewayService.SubcribeEvents_Request,
  proto.grpcMobileGatewayService.Empty_Response,
  /**
   * @param {!proto.grpcMobileGatewayService.SubcribeEvents_Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.grpcMobileGatewayService.Empty_Response.deserializeBinary
);


/**
 * @param {!proto.grpcMobileGatewayService.SubcribeEvents_Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.grpcMobileGatewayService.Empty_Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.grpcMobileGatewayService.Empty_Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServiceClient.prototype.subcribeEvents =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/SubcribeEvents',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_SubcribeEvents,
      callback);
};


/**
 * @param {!proto.grpcMobileGatewayService.SubcribeEvents_Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.grpcMobileGatewayService.Empty_Response>}
 *     Promise that resolves to the response
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServicePromiseClient.prototype.subcribeEvents =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/SubcribeEvents',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_SubcribeEvents);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.grpcMobileGatewayService.Register_Request,
 *   !proto.grpcMobileGatewayService.Register_Response>}
 */
const methodDescriptor_grpcMobileGatewayService_Register = new grpc.web.MethodDescriptor(
  '/grpcMobileGatewayService.grpcMobileGatewayService/Register',
  grpc.web.MethodType.UNARY,
  proto.grpcMobileGatewayService.Register_Request,
  proto.grpcMobileGatewayService.Register_Response,
  /**
   * @param {!proto.grpcMobileGatewayService.Register_Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.grpcMobileGatewayService.Register_Response.deserializeBinary
);


/**
 * @param {!proto.grpcMobileGatewayService.Register_Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.grpcMobileGatewayService.Register_Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.grpcMobileGatewayService.Register_Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServiceClient.prototype.register =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/Register',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_Register,
      callback);
};


/**
 * @param {!proto.grpcMobileGatewayService.Register_Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.grpcMobileGatewayService.Register_Response>}
 *     Promise that resolves to the response
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServicePromiseClient.prototype.register =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/Register',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_Register);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.grpcMobileGatewayService.ActiveAccount_Request,
 *   !proto.grpcMobileGatewayService.ActiveAccount_Response>}
 */
const methodDescriptor_grpcMobileGatewayService_ActiveAccount = new grpc.web.MethodDescriptor(
  '/grpcMobileGatewayService.grpcMobileGatewayService/ActiveAccount',
  grpc.web.MethodType.UNARY,
  proto.grpcMobileGatewayService.ActiveAccount_Request,
  proto.grpcMobileGatewayService.ActiveAccount_Response,
  /**
   * @param {!proto.grpcMobileGatewayService.ActiveAccount_Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.grpcMobileGatewayService.ActiveAccount_Response.deserializeBinary
);


/**
 * @param {!proto.grpcMobileGatewayService.ActiveAccount_Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.grpcMobileGatewayService.ActiveAccount_Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.grpcMobileGatewayService.ActiveAccount_Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServiceClient.prototype.activeAccount =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/ActiveAccount',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_ActiveAccount,
      callback);
};


/**
 * @param {!proto.grpcMobileGatewayService.ActiveAccount_Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.grpcMobileGatewayService.ActiveAccount_Response>}
 *     Promise that resolves to the response
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServicePromiseClient.prototype.activeAccount =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/ActiveAccount',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_ActiveAccount);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.grpcMobileGatewayService.Login_Request,
 *   !proto.grpcMobileGatewayService.Login_Response>}
 */
const methodDescriptor_grpcMobileGatewayService_Login = new grpc.web.MethodDescriptor(
  '/grpcMobileGatewayService.grpcMobileGatewayService/Login',
  grpc.web.MethodType.UNARY,
  proto.grpcMobileGatewayService.Login_Request,
  proto.grpcMobileGatewayService.Login_Response,
  /**
   * @param {!proto.grpcMobileGatewayService.Login_Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.grpcMobileGatewayService.Login_Response.deserializeBinary
);


/**
 * @param {!proto.grpcMobileGatewayService.Login_Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.grpcMobileGatewayService.Login_Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.grpcMobileGatewayService.Login_Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServiceClient.prototype.login =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/Login',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_Login,
      callback);
};


/**
 * @param {!proto.grpcMobileGatewayService.Login_Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.grpcMobileGatewayService.Login_Response>}
 *     Promise that resolves to the response
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServicePromiseClient.prototype.login =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/Login',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_Login);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.grpcMobileGatewayService.Logout_Request,
 *   !proto.grpcMobileGatewayService.Empty_Response>}
 */
const methodDescriptor_grpcMobileGatewayService_Logout = new grpc.web.MethodDescriptor(
  '/grpcMobileGatewayService.grpcMobileGatewayService/Logout',
  grpc.web.MethodType.UNARY,
  proto.grpcMobileGatewayService.Logout_Request,
  proto.grpcMobileGatewayService.Empty_Response,
  /**
   * @param {!proto.grpcMobileGatewayService.Logout_Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.grpcMobileGatewayService.Empty_Response.deserializeBinary
);


/**
 * @param {!proto.grpcMobileGatewayService.Logout_Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.grpcMobileGatewayService.Empty_Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.grpcMobileGatewayService.Empty_Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServiceClient.prototype.logout =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/Logout',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_Logout,
      callback);
};


/**
 * @param {!proto.grpcMobileGatewayService.Logout_Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.grpcMobileGatewayService.Empty_Response>}
 *     Promise that resolves to the response
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServicePromiseClient.prototype.logout =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/Logout',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_Logout);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.grpcMobileGatewayService.LoginByAccessToken_Request,
 *   !proto.grpcMobileGatewayService.LoginByAccessToken_Response>}
 */
const methodDescriptor_grpcMobileGatewayService_LoginByAccessToken = new grpc.web.MethodDescriptor(
  '/grpcMobileGatewayService.grpcMobileGatewayService/LoginByAccessToken',
  grpc.web.MethodType.UNARY,
  proto.grpcMobileGatewayService.LoginByAccessToken_Request,
  proto.grpcMobileGatewayService.LoginByAccessToken_Response,
  /**
   * @param {!proto.grpcMobileGatewayService.LoginByAccessToken_Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.grpcMobileGatewayService.LoginByAccessToken_Response.deserializeBinary
);


/**
 * @param {!proto.grpcMobileGatewayService.LoginByAccessToken_Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.grpcMobileGatewayService.LoginByAccessToken_Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.grpcMobileGatewayService.LoginByAccessToken_Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServiceClient.prototype.loginByAccessToken =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/LoginByAccessToken',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_LoginByAccessToken,
      callback);
};


/**
 * @param {!proto.grpcMobileGatewayService.LoginByAccessToken_Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.grpcMobileGatewayService.LoginByAccessToken_Response>}
 *     Promise that resolves to the response
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServicePromiseClient.prototype.loginByAccessToken =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/LoginByAccessToken',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_LoginByAccessToken);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.grpcMobileGatewayService.LinkAccount_Request,
 *   !proto.grpcMobileGatewayService.LinkAccount_Response>}
 */
const methodDescriptor_grpcMobileGatewayService_LinkAccount = new grpc.web.MethodDescriptor(
  '/grpcMobileGatewayService.grpcMobileGatewayService/LinkAccount',
  grpc.web.MethodType.UNARY,
  proto.grpcMobileGatewayService.LinkAccount_Request,
  proto.grpcMobileGatewayService.LinkAccount_Response,
  /**
   * @param {!proto.grpcMobileGatewayService.LinkAccount_Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.grpcMobileGatewayService.LinkAccount_Response.deserializeBinary
);


/**
 * @param {!proto.grpcMobileGatewayService.LinkAccount_Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.grpcMobileGatewayService.LinkAccount_Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.grpcMobileGatewayService.LinkAccount_Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServiceClient.prototype.linkAccount =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/LinkAccount',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_LinkAccount,
      callback);
};


/**
 * @param {!proto.grpcMobileGatewayService.LinkAccount_Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.grpcMobileGatewayService.LinkAccount_Response>}
 *     Promise that resolves to the response
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServicePromiseClient.prototype.linkAccount =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/LinkAccount',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_LinkAccount);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.grpcMobileGatewayService.RecoveryPasswordRequest_Request,
 *   !proto.grpcMobileGatewayService.RecoveryPasswordRequest_Response>}
 */
const methodDescriptor_grpcMobileGatewayService_RecoveryPasswordRequest = new grpc.web.MethodDescriptor(
  '/grpcMobileGatewayService.grpcMobileGatewayService/RecoveryPasswordRequest',
  grpc.web.MethodType.UNARY,
  proto.grpcMobileGatewayService.RecoveryPasswordRequest_Request,
  proto.grpcMobileGatewayService.RecoveryPasswordRequest_Response,
  /**
   * @param {!proto.grpcMobileGatewayService.RecoveryPasswordRequest_Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.grpcMobileGatewayService.RecoveryPasswordRequest_Response.deserializeBinary
);


/**
 * @param {!proto.grpcMobileGatewayService.RecoveryPasswordRequest_Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.grpcMobileGatewayService.RecoveryPasswordRequest_Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.grpcMobileGatewayService.RecoveryPasswordRequest_Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServiceClient.prototype.recoveryPasswordRequest =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/RecoveryPasswordRequest',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_RecoveryPasswordRequest,
      callback);
};


/**
 * @param {!proto.grpcMobileGatewayService.RecoveryPasswordRequest_Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.grpcMobileGatewayService.RecoveryPasswordRequest_Response>}
 *     Promise that resolves to the response
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServicePromiseClient.prototype.recoveryPasswordRequest =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/RecoveryPasswordRequest',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_RecoveryPasswordRequest);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.grpcMobileGatewayService.RecoveryPasswordSubmit_Request,
 *   !proto.grpcMobileGatewayService.Empty_Response>}
 */
const methodDescriptor_grpcMobileGatewayService_RecoveryPasswordSubmit = new grpc.web.MethodDescriptor(
  '/grpcMobileGatewayService.grpcMobileGatewayService/RecoveryPasswordSubmit',
  grpc.web.MethodType.UNARY,
  proto.grpcMobileGatewayService.RecoveryPasswordSubmit_Request,
  proto.grpcMobileGatewayService.Empty_Response,
  /**
   * @param {!proto.grpcMobileGatewayService.RecoveryPasswordSubmit_Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.grpcMobileGatewayService.Empty_Response.deserializeBinary
);


/**
 * @param {!proto.grpcMobileGatewayService.RecoveryPasswordSubmit_Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.grpcMobileGatewayService.Empty_Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.grpcMobileGatewayService.Empty_Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServiceClient.prototype.recoveryPasswordSubmit =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/RecoveryPasswordSubmit',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_RecoveryPasswordSubmit,
      callback);
};


/**
 * @param {!proto.grpcMobileGatewayService.RecoveryPasswordSubmit_Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.grpcMobileGatewayService.Empty_Response>}
 *     Promise that resolves to the response
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServicePromiseClient.prototype.recoveryPasswordSubmit =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/RecoveryPasswordSubmit',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_RecoveryPasswordSubmit);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.grpcMobileGatewayService.OpenGameLog_Request,
 *   !proto.grpcMobileGatewayService.Empty_Response>}
 */
const methodDescriptor_grpcMobileGatewayService_OpenGameLog = new grpc.web.MethodDescriptor(
  '/grpcMobileGatewayService.grpcMobileGatewayService/OpenGameLog',
  grpc.web.MethodType.UNARY,
  proto.grpcMobileGatewayService.OpenGameLog_Request,
  proto.grpcMobileGatewayService.Empty_Response,
  /**
   * @param {!proto.grpcMobileGatewayService.OpenGameLog_Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.grpcMobileGatewayService.Empty_Response.deserializeBinary
);


/**
 * @param {!proto.grpcMobileGatewayService.OpenGameLog_Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.grpcMobileGatewayService.Empty_Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.grpcMobileGatewayService.Empty_Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServiceClient.prototype.openGameLog =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/OpenGameLog',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_OpenGameLog,
      callback);
};


/**
 * @param {!proto.grpcMobileGatewayService.OpenGameLog_Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.grpcMobileGatewayService.Empty_Response>}
 *     Promise that resolves to the response
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServicePromiseClient.prototype.openGameLog =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/OpenGameLog',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_OpenGameLog);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.grpcMobileGatewayService.InstallGameLog_Request,
 *   !proto.grpcMobileGatewayService.Empty_Response>}
 */
const methodDescriptor_grpcMobileGatewayService_InstallGameLog = new grpc.web.MethodDescriptor(
  '/grpcMobileGatewayService.grpcMobileGatewayService/InstallGameLog',
  grpc.web.MethodType.UNARY,
  proto.grpcMobileGatewayService.InstallGameLog_Request,
  proto.grpcMobileGatewayService.Empty_Response,
  /**
   * @param {!proto.grpcMobileGatewayService.InstallGameLog_Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.grpcMobileGatewayService.Empty_Response.deserializeBinary
);


/**
 * @param {!proto.grpcMobileGatewayService.InstallGameLog_Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.grpcMobileGatewayService.Empty_Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.grpcMobileGatewayService.Empty_Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServiceClient.prototype.installGameLog =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/InstallGameLog',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_InstallGameLog,
      callback);
};


/**
 * @param {!proto.grpcMobileGatewayService.InstallGameLog_Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.grpcMobileGatewayService.Empty_Response>}
 *     Promise that resolves to the response
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServicePromiseClient.prototype.installGameLog =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/InstallGameLog',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_InstallGameLog);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.grpcMobileGatewayService.GetProfile_Request,
 *   !proto.grpcMobileGatewayService.GetProfile_Response>}
 */
const methodDescriptor_grpcMobileGatewayService_GetProfile = new grpc.web.MethodDescriptor(
  '/grpcMobileGatewayService.grpcMobileGatewayService/GetProfile',
  grpc.web.MethodType.UNARY,
  proto.grpcMobileGatewayService.GetProfile_Request,
  proto.grpcMobileGatewayService.GetProfile_Response,
  /**
   * @param {!proto.grpcMobileGatewayService.GetProfile_Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.grpcMobileGatewayService.GetProfile_Response.deserializeBinary
);


/**
 * @param {!proto.grpcMobileGatewayService.GetProfile_Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.grpcMobileGatewayService.GetProfile_Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.grpcMobileGatewayService.GetProfile_Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServiceClient.prototype.getProfile =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/GetProfile',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_GetProfile,
      callback);
};


/**
 * @param {!proto.grpcMobileGatewayService.GetProfile_Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.grpcMobileGatewayService.GetProfile_Response>}
 *     Promise that resolves to the response
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServicePromiseClient.prototype.getProfile =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/GetProfile',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_GetProfile);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.grpcMobileGatewayService.SdkInit_Request,
 *   !proto.grpcMobileGatewayService.SdkInit_Response>}
 */
const methodDescriptor_grpcMobileGatewayService_SdkInit = new grpc.web.MethodDescriptor(
  '/grpcMobileGatewayService.grpcMobileGatewayService/SdkInit',
  grpc.web.MethodType.UNARY,
  proto.grpcMobileGatewayService.SdkInit_Request,
  proto.grpcMobileGatewayService.SdkInit_Response,
  /**
   * @param {!proto.grpcMobileGatewayService.SdkInit_Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.grpcMobileGatewayService.SdkInit_Response.deserializeBinary
);


/**
 * @param {!proto.grpcMobileGatewayService.SdkInit_Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.grpcMobileGatewayService.SdkInit_Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.grpcMobileGatewayService.SdkInit_Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServiceClient.prototype.sdkInit =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/SdkInit',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_SdkInit,
      callback);
};


/**
 * @param {!proto.grpcMobileGatewayService.SdkInit_Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.grpcMobileGatewayService.SdkInit_Response>}
 *     Promise that resolves to the response
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServicePromiseClient.prototype.sdkInit =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/SdkInit',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_SdkInit);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.grpcMobileGatewayService.ResendOTP_Request,
 *   !proto.grpcMobileGatewayService.ResendOTP_Response>}
 */
const methodDescriptor_grpcMobileGatewayService_ResendOTP = new grpc.web.MethodDescriptor(
  '/grpcMobileGatewayService.grpcMobileGatewayService/ResendOTP',
  grpc.web.MethodType.UNARY,
  proto.grpcMobileGatewayService.ResendOTP_Request,
  proto.grpcMobileGatewayService.ResendOTP_Response,
  /**
   * @param {!proto.grpcMobileGatewayService.ResendOTP_Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.grpcMobileGatewayService.ResendOTP_Response.deserializeBinary
);


/**
 * @param {!proto.grpcMobileGatewayService.ResendOTP_Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.grpcMobileGatewayService.ResendOTP_Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.grpcMobileGatewayService.ResendOTP_Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServiceClient.prototype.resendOTP =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/ResendOTP',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_ResendOTP,
      callback);
};


/**
 * @param {!proto.grpcMobileGatewayService.ResendOTP_Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.grpcMobileGatewayService.ResendOTP_Response>}
 *     Promise that resolves to the response
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServicePromiseClient.prototype.resendOTP =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/ResendOTP',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_ResendOTP);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.grpcMobileGatewayService.RequestActive_Request,
 *   !proto.grpcMobileGatewayService.RequestActive_Response>}
 */
const methodDescriptor_grpcMobileGatewayService_RequestActive = new grpc.web.MethodDescriptor(
  '/grpcMobileGatewayService.grpcMobileGatewayService/RequestActive',
  grpc.web.MethodType.UNARY,
  proto.grpcMobileGatewayService.RequestActive_Request,
  proto.grpcMobileGatewayService.RequestActive_Response,
  /**
   * @param {!proto.grpcMobileGatewayService.RequestActive_Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.grpcMobileGatewayService.RequestActive_Response.deserializeBinary
);


/**
 * @param {!proto.grpcMobileGatewayService.RequestActive_Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.grpcMobileGatewayService.RequestActive_Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.grpcMobileGatewayService.RequestActive_Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServiceClient.prototype.requestActive =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/RequestActive',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_RequestActive,
      callback);
};


/**
 * @param {!proto.grpcMobileGatewayService.RequestActive_Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.grpcMobileGatewayService.RequestActive_Response>}
 *     Promise that resolves to the response
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServicePromiseClient.prototype.requestActive =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/RequestActive',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_RequestActive);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.grpcMobileGatewayService.IAPInit_Request,
 *   !proto.grpcMobileGatewayService.IAPInit_Response>}
 */
const methodDescriptor_grpcMobileGatewayService_IAPInit = new grpc.web.MethodDescriptor(
  '/grpcMobileGatewayService.grpcMobileGatewayService/IAPInit',
  grpc.web.MethodType.UNARY,
  proto.grpcMobileGatewayService.IAPInit_Request,
  proto.grpcMobileGatewayService.IAPInit_Response,
  /**
   * @param {!proto.grpcMobileGatewayService.IAPInit_Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.grpcMobileGatewayService.IAPInit_Response.deserializeBinary
);


/**
 * @param {!proto.grpcMobileGatewayService.IAPInit_Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.grpcMobileGatewayService.IAPInit_Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.grpcMobileGatewayService.IAPInit_Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServiceClient.prototype.iAPInit =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/IAPInit',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_IAPInit,
      callback);
};


/**
 * @param {!proto.grpcMobileGatewayService.IAPInit_Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.grpcMobileGatewayService.IAPInit_Response>}
 *     Promise that resolves to the response
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServicePromiseClient.prototype.iAPInit =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/IAPInit',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_IAPInit);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.grpcMobileGatewayService.FinalizeIAP_Request,
 *   !proto.grpcMobileGatewayService.Empty_Response>}
 */
const methodDescriptor_grpcMobileGatewayService_FinalizeIAP = new grpc.web.MethodDescriptor(
  '/grpcMobileGatewayService.grpcMobileGatewayService/FinalizeIAP',
  grpc.web.MethodType.UNARY,
  proto.grpcMobileGatewayService.FinalizeIAP_Request,
  proto.grpcMobileGatewayService.Empty_Response,
  /**
   * @param {!proto.grpcMobileGatewayService.FinalizeIAP_Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.grpcMobileGatewayService.Empty_Response.deserializeBinary
);


/**
 * @param {!proto.grpcMobileGatewayService.FinalizeIAP_Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.grpcMobileGatewayService.Empty_Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.grpcMobileGatewayService.Empty_Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServiceClient.prototype.finalizeIAP =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/FinalizeIAP',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_FinalizeIAP,
      callback);
};


/**
 * @param {!proto.grpcMobileGatewayService.FinalizeIAP_Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.grpcMobileGatewayService.Empty_Response>}
 *     Promise that resolves to the response
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServicePromiseClient.prototype.finalizeIAP =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/FinalizeIAP',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_FinalizeIAP);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.grpcMobileGatewayService.DeleteAccount_Request,
 *   !proto.grpcMobileGatewayService.Empty_Response>}
 */
const methodDescriptor_grpcMobileGatewayService_DeleteAccount = new grpc.web.MethodDescriptor(
  '/grpcMobileGatewayService.grpcMobileGatewayService/DeleteAccount',
  grpc.web.MethodType.UNARY,
  proto.grpcMobileGatewayService.DeleteAccount_Request,
  proto.grpcMobileGatewayService.Empty_Response,
  /**
   * @param {!proto.grpcMobileGatewayService.DeleteAccount_Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.grpcMobileGatewayService.Empty_Response.deserializeBinary
);


/**
 * @param {!proto.grpcMobileGatewayService.DeleteAccount_Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.grpcMobileGatewayService.Empty_Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.grpcMobileGatewayService.Empty_Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServiceClient.prototype.deleteAccount =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/DeleteAccount',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_DeleteAccount,
      callback);
};


/**
 * @param {!proto.grpcMobileGatewayService.DeleteAccount_Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.grpcMobileGatewayService.Empty_Response>}
 *     Promise that resolves to the response
 */
proto.grpcMobileGatewayService.grpcMobileGatewayServicePromiseClient.prototype.deleteAccount =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/grpcMobileGatewayService.grpcMobileGatewayService/DeleteAccount',
      request,
      metadata || {},
      methodDescriptor_grpcMobileGatewayService_DeleteAccount);
};


module.exports = proto.grpcMobileGatewayService;

